services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'    # Główny port dla stron HTTP
      - '81:81'    # Panel administratora NPM
      - '443:443'  # Główny port dla stron HTTPS (SSL)
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  npm_data:
  npm_letsencrypt:
